# yamllint disable rule:line-length
---
# For more info check: https://github.com/ansible-collections/google.cloud/blob/master/plugins/inventory/gcp_compute.py
plugin: gcp_compute
projects:
  - chromatic-being-340302
auth_kind: serviceaccount
service_account_file: ansible_sa_key.json
keyed_groups:
  - key: labels.kind
    prefix: k8s
hostnames:
  # List host by name instead of the default public ip
  - name
compose:
  # Set an inventory parameter to use the Public IP address to connect to the host
  # For Private ip use "networkInterfaces[0].networkIP"
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
